// Photo variable configuration: default list and translation key map.

class PhotoVariables {
  PhotoVariables._();

  /// Default ordered list of photo variable names.
  static const List<String> defaultList = [
    'vor Umbau',
    'Erdung_1',
    'Erdung_2',
    'Rack_Gesamtansicht',
    'OSN und ROUTER Gesamtansicht',
    'Stromkabel_Beschriftung',
    'Stromkabel_Beschriftung_2',
    'Beschriftung vom Gerät',
    'Beschriftung am Gerät_1',
    'Beschriftung am Gerät_2',
    'Beschriftung am Gerät_3',
    'Beschriftung am Gerät_4',
    'Beschriftung am Gerät_5',
    'Beschriftung am Gerät_6',
    'Beschriftung am Gerät_7',
    'Beschriftung am Gerät_8',
    'Spleißbox & Cube',
    'Beschriftung ODF_1',
    'Beschriftung ODF_2',
    'Beschriftung Sicherungen_1',
    'Beschriftung Sicherungen_2',
    'Powerbox_1',
    'Stromkabel_Beschriftung_Powerbox_2',
    'SFP_Erweiterung',
    'Tresor',
    'Gerät_Alt',
    'Erweiterung_B_Seite',
    'DGUV',
    'Elektromessprotokoll',
    'DGUV_vor_Ort',
    'Elektromessprotokoll_vor_Ort',
    'Sicherungsgröße',
    'Bilder_B_Seite_1',
    'Bilder_B_Seite_2',
    'Bilder_B_Seite_3',
  ];

  /// Mapping: German variable name → translation key.
  static const Map<String, String> translationKeys = {
    'vor Umbau': 'photo_vor_umbau',
    'Erdung_1': 'photo_erdung_1',
    'Erdung_2': 'photo_erdung_2',
    'Rack_Gesamtansicht': 'photo_rack_gesamtansicht',
    'OSN und ROUTER Gesamtansicht': 'photo_osn_router',
    'Stromkabel_Beschriftung': 'photo_stromkabel_beschriftung',
    'Stromkabel_Beschriftung_2': 'photo_stromkabel_beschriftung_2',
    'Beschriftung vom Geraet': 'photo_beschriftung_vom_geraet',
    'Beschriftung am Geraet_1': 'photo_beschriftung_am_geraet_1',
    'Beschriftung am Geraet_2': 'photo_beschriftung_am_geraet_2',
    'Beschriftung am Geraet_3': 'photo_beschriftung_am_geraet_3',
    'Beschriftung am Geraet_4': 'photo_beschriftung_am_geraet_4',
    'Beschriftung am Geraet_5': 'photo_beschriftung_am_geraet_5',
    'Beschriftung am Geraet_6': 'photo_beschriftung_am_geraet_6',
    'Beschriftung am Geraet_7': 'photo_beschriftung_am_geraet_7',
    'Beschriftung am Geraet_8': 'photo_beschriftung_am_geraet_8',
    'Spleißbox & Cube': 'photo_spleissbox_cube',
    'Beschriftung ODF_1': 'photo_beschriftung_odf_1',
    'Beschriftung ODF_2': 'photo_beschriftung_odf_2',
    'Beschriftung Sicherungen_1': 'photo_beschriftung_sicherungen_1',
    'Beschriftung Sicherungen_2': 'photo_beschriftung_sicherungen_2',
    'Powerbox_1': 'photo_powerbox_1',
    'Stromkabel_Beschriftung_Powerbox_2': 'photo_stromkabel_powerbox_2',
    'SFP_Erweiterung': 'photo_sfp_erweiterung',
    'Tresor': 'photo_tresor',
    'Gerät_Alt': 'photo_geraet_alt',
    'Erweiterung_B_Seite': 'photo_erweiterung_b_seite',
    'DGUV': 'photo_dguv',
    'Elektromessprotokoll': 'photo_elektromessprotokoll',
    'DGUV_vor_Ort': 'photo_dguv_vor_ort',
    'Elektromessprotokoll_vor_Ort': 'photo_elektromessprotokoll_vor_ort',
    'Sicherungsgröße': 'photo_sicherungsgroesse',
    'Bilder_B_Seite_1': 'photo_bilder_b_seite_1',
    'Bilder_B_Seite_2': 'photo_bilder_b_seite_2',
    'Bilder_B_Seite_3': 'photo_bilder_b_seite_3',
  };
}
